# Generated by Django 2.2.1 on 2020-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedShippingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('num', models.FloatField(max_length=20)),
                ('type_of_shipping', models.CharField(max_length=10)),
                ('arrival_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('num', models.FloatField(max_length=20)),
                ('warehouse', models.CharField(max_length=10)),
                ('warehouse_admin', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransportationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('num', models.FloatField(max_length=20)),
                ('collection_center', models.CharField(max_length=6)),
                ('inspection_and_warehousing', models.CharField(max_length=6)),
                ('in_warehousing', models.CharField(max_length=6)),
                ('Warehouse', models.CharField(max_length=10)),
                ('re_out_warehousing', models.CharField(max_length=6)),
                ('out_warehousing', models.CharField(max_length=6)),
                ('loading_and_distribution', models.CharField(max_length=6)),
                ('car_num', models.CharField(max_length=6)),
                ('arrival_station', models.CharField(max_length=6)),
                ('confirm_receipt', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=10)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('num', models.FloatField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse', models.CharField(max_length=10)),
                ('supplier_name', models.CharField(max_length=20)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('num', models.FloatField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('channel', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse', models.CharField(max_length=10)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('num', models.FloatField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('location', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse', models.CharField(max_length=10)),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('num', models.FloatField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('Specification', models.CharField(max_length=20)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('num', models.FloatField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('phone235', models.CharField(max_length=11)),
                ('user_name', models.CharField(max_length=20)),
                ('adress', models.TextField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=20)),
                ('start_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
                ('unit_of_measurement', models.CharField(max_length=6)),
                ('num', models.FloatField(max_length=20)),
                ('mileage', models.FloatField(max_length=20)),
                ('accepted_by', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
